name: Increment Git Tag
description: Increment git tag based on the provided version type
inputs:
  version-type:
    description: Provide semantic version type [major, minor, patch]
    required: true
    default: patch
outputs:
  new-version:
    description: Incremented version based on the input
runs:
  using: "node20"
  main: "./action/index.js"
